import LegalLayout, { Section, Bullets, LEGAL_CONTACT } from '../components/LegalLayout';

export default function Terms() {
  return (
    <LegalLayout
      title="Terms of Service"
      intro="These terms cover what VaaniTutor offers, what you pay for, and what you can reasonably expect from it."
    >
      <Section heading="Using the app">
        <p>
          By creating an account you agree to these terms. VaaniTutor is an educational tool for practising spoken
          Indian languages. You must be at least 13 years old to use it.
        </p>
        <Bullets
          items={[
            'Keep your login details to yourself — you are responsible for activity on your account.',
            'Give an email address you actually control, since verification and password resets go there.',
            'Do not attempt to break, overload or gain unauthorised access to the service or other learners’ data.',
            'Do not use the app to produce unlawful, abusive or harassing content.',
          ]}
        />
      </Section>

      <Section heading="Free and Premium">
        <Bullets
          items={[
            'Your first two practice sessions are free, in any language and of any length.',
            'From the third session onward the account must be Premium.',
            'Premium is a one-time payment of ₹299. It is not a subscription — there is no renewal, and nothing is charged to you again.',
            'Premium unlocks unlimited sessions, five-turn conversational roleplay in the Speak activity, progress analytics, all eleven languages and roadmap regeneration.',
          ]}
        />
        <p>
          A session counts against your free allowance when it is first started, not when you resume one you already
          began. Leaving a session part-way through and returning later does not use another.
        </p>
      </Section>

      <Section heading="Payments and refunds">
        <p>
          Payments are handled by Razorpay. We never see your card or banking details. Prices are in Indian Rupees and
          include any applicable taxes.
        </p>
        <p>
          Because Premium unlocks immediately and in full, purchases are generally non-refundable. If something went
          wrong — you were charged twice, the payment succeeded but Premium did not activate, or you were billed in
          error — email{' '}
          <a href={`mailto:${LEGAL_CONTACT}`} className="font-semibold text-brand hover:underline">
            {LEGAL_CONTACT}
          </a>{' '}
          within 7 days and we will investigate and refund where the charge was not properly earned.
        </p>
      </Section>

      <Section heading="What the AI can and cannot do">
        <p>
          Corrections, fluency scores, roadmaps and quiz questions are generated by automated language and speech
          models. They are useful practice, but they are not a qualified teacher.
        </p>
        <Bullets
          items={[
            'Transcription can misread what you said, particularly in noisy surroundings or with an unfamiliar accent.',
            'Corrections and grammar explanations can occasionally be wrong or oversimplified.',
            'Fluency scores are indicative only. They are not a certification and carry no formal standing.',
            'Do not rely on the app for exam preparation, legal, medical, professional or safety-critical translation.',
          ]}
        />
      </Section>

      <Section heading="Availability">
        <p>
          This is an independent project running largely on free service tiers. The app may be slow to wake after a
          quiet period, and speech or language features may be briefly unavailable if an upstream provider is down or
          a usage quota is reached. We aim to keep it working but do not promise uninterrupted service, and we may
          change or discontinue features.
        </p>
      </Section>

      <Section heading="Your content">
        <p>
          What you say and write stays yours. You grant us only the permission needed to run the service: to process
          your recording into text, assess it, generate a reply, and store your transcript and progress so you can see
          your history. We do not use your recordings or transcripts to train our own models, and we do not publish
          them.
        </p>
      </Section>

      <Section heading="Ending your account">
        <p>
          You can ask us to delete your account at any time by email. We may suspend accounts that abuse the service,
          attempt to breach its security, or try to access other learners’ data. If we close your account for such a
          reason, any Premium payment is not refunded.
        </p>
      </Section>

      <Section heading="Liability">
        <p>
          VaaniTutor is provided “as is”, without warranties of any kind. To the extent the law allows, we are not
          liable for indirect or consequential loss arising from your use of the app, and our total liability to you
          is limited to the amount you have actually paid us.
        </p>
      </Section>

      <Section heading="Governing law and changes">
        <p>
          These terms are governed by the laws of India. If we change them we will update this page and the date at
          the top; continuing to use the app means you accept the revised terms.
        </p>
      </Section>
    </LegalLayout>
  );
}
