import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { CheckCircle2, Lock, Play, HelpCircle, BookOpen, MessageSquare, ChevronDown, ChevronRight, Sparkles } from 'lucide-react';

export default function RoadmapTimeline({ roadmap, currentDayNumber = 1, languageCode }) {
  const navigate = useNavigate();
  const [expandedWeek, setExpandedWeek] = useState(1);
  const [selectedDay, setSelectedDay] = useState(null);

  if (!roadmap || !roadmap.weeks || roadmap.weeks.length === 0) {
    return (
      <div className="p-12 text-center text-slate-400 bg-slate-900/60 rounded-3xl border border-slate-800">
        No roadmap generated yet. Complete onboarding to generate your curriculum.
      </div>
    );
  }

  const startPractice = (dayNum) => {
    navigate(`/practice/${languageCode}?day=${dayNum}`);
  };

  return (
    <div className="space-y-6">
      {/* Roadmap Header Summary */}
      <div className="bg-slate-900/80 border border-slate-800/80 rounded-3xl p-6 sm:p-8 backdrop-blur-xl relative overflow-hidden">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 text-indigo-400 text-xs font-semibold mb-2 border border-indigo-500/20">
              <Sparkles className="w-3.5 h-3.5" /> Generated by {roadmap.generatedBy || 'Indic LLM'}
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              Personalized {roadmap.languageCode} Curriculum
            </h1>
            <p className="text-slate-400 text-sm mt-1">
              {roadmap.totalDays} Days • Level: <span className="text-indigo-400 font-semibold">{roadmap.startLevel}</span> • {roadmap.weeks.length} Structured Weeks
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={() => startPractice(currentDayNumber)}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl bg-gradient-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 text-white font-bold text-sm transition-all shadow-xl shadow-indigo-600/30 cursor-pointer"
            >
              <Play className="w-4 h-4 fill-white" /> Start Day {currentDayNumber} Practice
            </button>
          </div>
        </div>
      </div>

      {/* Week Accordion & Day Timeline */}
      <div className="space-y-4">
        {roadmap.weeks.map((week) => {
          const isExpanded = expandedWeek === week.weekNumber;
          const weekDays = week.days || [];
          const completedInWeek = weekDays.filter((d) => d.completedAt).length;

          return (
            <div
              key={week.weekNumber}
              className="bg-slate-900/80 border border-slate-800/80 rounded-3xl overflow-hidden backdrop-blur-xl transition-all"
            >
              {/* Week Accordion Header */}
              <button
                type="button"
                onClick={() => setExpandedWeek(isExpanded ? null : week.weekNumber)}
                className="w-full flex items-center justify-between p-5 sm:p-6 text-left hover:bg-slate-800/30 transition cursor-pointer"
              >
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 font-bold flex items-center justify-center text-sm">
                    W{week.weekNumber}
                  </div>
                  <div>
                    <div className="text-xs font-semibold uppercase tracking-wider text-indigo-400">
                      Week {week.weekNumber}
                    </div>
                    <div className="text-base sm:text-lg font-bold text-white mt-0.5">
                      {week.theme}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <span className="text-xs font-mono text-slate-400 hidden sm:inline-block">
                    {completedInWeek}/{weekDays.length} Completed
                  </span>
                  {isExpanded ? (
                    <ChevronDown className="w-5 h-5 text-slate-400" />
                  ) : (
                    <ChevronRight className="w-5 h-5 text-slate-400" />
                  )}
                </div>
              </button>

              {/* Day Cards in Week */}
              {isExpanded && (
                <div className="p-5 sm:p-6 pt-0 border-t border-slate-800/60 grid grid-cols-1 md:grid-cols-2 gap-4">
                  {weekDays.map((day) => {
                    const isCompleted = !!day.completedAt;
                    const isCurrent = day.dayNumber === currentDayNumber;
                    const isLocked = day.dayNumber > currentDayNumber && !isCompleted;

                    return (
                      <div
                        key={day.dayNumber}
                        onClick={() => setSelectedDay(day)}
                        className={`p-5 rounded-2xl border transition-all cursor-pointer relative overflow-hidden ${
                          isCurrent
                            ? 'bg-indigo-600/15 border-indigo-500/80 ring-2 ring-indigo-500/20 shadow-lg shadow-indigo-500/10'
                            : isCompleted
                            ? 'bg-emerald-950/15 border-emerald-500/40 hover:border-emerald-500/60'
                            : isLocked
                            ? 'bg-slate-900/40 border-slate-800/60 opacity-75'
                            : 'bg-slate-800/40 border-slate-700/60 hover:border-slate-600'
                        }`}
                      >
                        <div className="flex items-start justify-between gap-2 mb-3">
                          <div className="flex items-center gap-2">
                            <span className="px-2.5 py-1 rounded-lg text-xs font-bold font-mono bg-slate-800 text-indigo-300 border border-slate-700">
                              Day {day.dayNumber}
                            </span>
                            {isCurrent && (
                              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold uppercase bg-amber-500/20 text-amber-300 border border-amber-500/30">
                                Today
                              </span>
                            )}
                          </div>

                          <div>
                            {isCompleted ? (
                              <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                            ) : isLocked ? (
                              <Lock className="w-4 h-4 text-slate-500" />
                            ) : (
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  startPractice(day.dayNumber);
                                }}
                                className="p-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold transition shadow-md shadow-indigo-600/30"
                              >
                                <Play className="w-3.5 h-3.5 fill-white" />
                              </button>
                            )}
                          </div>
                        </div>

                        <h4 className="text-base font-bold text-white line-clamp-1">{day.topic}</h4>
                        <p className="text-xs text-slate-400 mt-1 line-clamp-2">{day.scenario}</p>

                        {/* Target phrases & Quiz tags */}
                        <div className="flex items-center gap-2 mt-4 pt-3 border-t border-slate-800/80 text-[11px] text-slate-400 font-mono">
                          <span className="inline-flex items-center gap-1">
                            <MessageSquare className="w-3.5 h-3.5 text-indigo-400" /> {day.targetPhrases?.length || 0} Phrases
                          </span>
                          <span>•</span>
                          <span className="inline-flex items-center gap-1">
                            <HelpCircle className="w-3.5 h-3.5 text-amber-400" /> {day.quiz?.length || 0} Quiz Qs
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Selected Day Preview Modal */}
      {selectedDay && (
        <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl max-w-xl w-full p-6 sm:p-8 space-y-6 shadow-2xl relative">
            <div className="flex items-start justify-between">
              <div>
                <span className="px-3 py-1 rounded-full text-xs font-bold font-mono bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                  Day {selectedDay.dayNumber} Overview
                </span>
                <h3 className="text-xl font-bold text-white mt-2">{selectedDay.topic}</h3>
                <p className="text-xs text-slate-400 mt-1">{selectedDay.scenario}</p>
              </div>
              <button
                onClick={() => setSelectedDay(null)}
                className="text-slate-400 hover:text-white p-2 rounded-xl bg-slate-800 text-sm font-bold"
              >
                ✕
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div className="p-4 rounded-2xl bg-slate-800/40 border border-slate-700/60">
                <div className="font-semibold text-indigo-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <MessageSquare className="w-4 h-4" /> Practice Prompt
                </div>
                <div className="text-sm font-semibold text-white">{selectedDay.promptText}</div>
                {selectedDay.translationEnglish && (
                  <div className="text-slate-400 mt-1 italic">"{selectedDay.translationEnglish}"</div>
                )}
              </div>

              {selectedDay.grammarFocus && (
                <div className="p-4 rounded-2xl bg-slate-800/40 border border-slate-700/60">
                  <div className="font-semibold text-amber-300 uppercase tracking-wider mb-1 flex items-center gap-1.5">
                    <BookOpen className="w-4 h-4" /> Grammar Rule
                  </div>
                  <div className="text-slate-300 leading-relaxed">{selectedDay.grammarFocus}</div>
                </div>
              )}

              {selectedDay.quiz && selectedDay.quiz.length > 0 && (
                <div className="p-4 rounded-2xl bg-slate-800/40 border border-slate-700/60">
                  <div className="font-semibold text-emerald-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                    <HelpCircle className="w-4 h-4" /> Daily Multiple Choice Quiz ({selectedDay.quiz.length} Questions)
                  </div>
                  <div className="text-slate-400 font-sans">
                    Includes interactive recall questions testing vocabulary and grammar retention.
                  </div>
                </div>
              )}
            </div>

            <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-800">
              <button
                onClick={() => setSelectedDay(null)}
                className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold"
              >
                Close
              </button>
              <button
                onClick={() => {
                  setSelectedDay(null);
                  startPractice(selectedDay.dayNumber);
                }}
                className="px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold transition shadow-lg shadow-indigo-600/30"
              >
                Start Practice Now
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
